# Generated by Django 3.0.5 on 2021-02-03 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rooms', models.CharField(max_length=100)),
                ('AcRooms', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('Room_Type', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('Cost', models.CharField(max_length=100)),
                ('Owner_Id', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('Offer', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=50)),
                ('Phone_No', models.CharField(max_length=10)),
                ('img', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=50)),
                ('Phone_No', models.CharField(max_length=10)),
                ('img', models.ImageField(upload_to='pics')),
                ('Members', models.IntegerField()),
                ('Purpose', models.CharField(max_length=100)),
                ('Joining_date', models.DateField()),
                ('Leave_date', models.DateField()),
                ('Address', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
    ]
